services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ironman
      POSTGRES_PASSWORD: ironman
      POSTGRES_DB: ironman
    ports:
      - "5432:5432"
    volumes:
      - ironman-postgres:/var/lib/postgresql/data

volumes:
  ironman-postgres:
